# Generated by Django 2.1.5 on 2019-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField()),
                ('url', models.CharField(max_length=140)),
                ('describtion', models.TextField()),
            ],
        ),
    ]
